name: rain
description: Weather application

publish_to: "none"

version: 1.3.9+42

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: "^3.38.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  gap: ^3.0.1
  dio: ^5.9.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  latlong2: ^0.9.1
  timezone: ^0.10.1
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  home_widget: ^0.8.1
  restart_app: ^1.3.2
  flutter_map: ^8.2.2
  display_mode: ^0.0.2
  workmanager: ^0.9.0+3
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2
  iconsax_plus: ^1.0.0
  dynamic_color: ^1.8.1
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  flutter_timezone: ^5.0.1
  device_info_plus: ^12.2.0
  package_info_plus: ^9.0.0
  connectivity_plus: ^7.0.0
  freezed_annotation: ^3.1.0
  flutter_map_cache: ^2.0.0+1
  lat_lng_to_timezone: ^0.2.0
  line_awesome_flutter: ^3.0.1
  dio_cache_interceptor: ^4.0.5
  http_cache_file_store: ^2.0.1
  flutter_map_animations: ^0.9.0
  flutter_expandable_fab: ^2.5.2
  flutter_hsvcolor_picker: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^19.5.0
  internet_connection_checker_plus: ^2.9.1
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

# Uncomment this for publishing FLOSS variant
# dependency_overrides:
#   geolocator_android:
#     git:
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  isar_community_generator: ^3.3.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
