name: rain
description: Weather application

publish_to: "none"

version: 1.3.2+35

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  dio: ^5.5.0+1
  intl: ^0.19.0
  isar: 
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  shimmer: ^3.0.0
  iconsax: ^0.0.8
  timezone: ^0.9.4
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  home_widget: ^0.6.0
  workmanager: ^0.5.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  time_machine: ^0.9.17
  flutter_glow:
    git:
      url: https://github.com/payam-zahedi/flutter-glow.git
  dynamic_color: ^1.7.0
  path_provider: ^2.1.3
  # quick_settings: ^1.0.1
  json_annotation: ^4.9.0
  flutter_timezone: ^2.0.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  connectivity_plus: ^6.0.3
  freezed_annotation: ^2.4.3
  isar_flutter_libs:
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  flutter_displaymode: ^0.6.0
  lat_lng_to_timezone: ^0.2.0
  # font_awesome_flutter: ^10.7.0
  flutter_hsvcolor_picker: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^17.2.1+1
  internet_connection_checker_plus: ^2.5.0

# Uncomment this for publishing FLOSS variant
# dependency_overrides:
#   geolocator_android:
#     git:
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  isar_generator: 
    version: ^3.1.7
    hosted: https://pub.isar-community.dev/
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
