name: rain
description: Weather application

publish_to: "none"

version: 1.3.6+39

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  gap: ^3.0.1
  dio: ^5.7.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  latlong2: ^0.9.1
  timezone: ^0.9.4
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  home_widget: ^0.7.0
  workmanager: ^0.5.2
  restart_app: ^1.3.2
  flutter_map: ^7.0.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  iconsax_plus: ^1.0.0
  time_machine: ^0.9.17
  dynamic_color: ^1.7.0
  path_provider: ^2.1.5
  # quick_settings: ^1.0.1
  json_annotation: ^4.9.0
  flutter_timezone: ^3.0.1
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  connectivity_plus: ^6.1.0
  flutter_map_cache: ^1.5.1
  freezed_annotation: ^2.4.4
  flutter_displaymode: ^0.6.0
  lat_lng_to_timezone: ^0.2.0
  line_awesome_flutter: ^3.0.1
  dio_cache_interceptor: ^3.5.0
  flutter_map_animations: ^0.7.1
  flutter_expandable_fab: ^2.3.0
  flutter_hsvcolor_picker: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^18.0.0
  internet_connection_checker_plus: ^2.5.2
  dio_cache_interceptor_file_store: ^1.2.2
  isar:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

# Uncomment this for publishing FLOSS variant
# dependency_overrides:
#   geolocator_android:
#     git:
#       url: https://github.com/Zverik/flutter-geolocator.git
#       ref: floss
#       path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  isar_generator:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
